config/routes.rb
KF::Application.routes.draw do
  resources :assemblies

  devise_for :users
  
  match 'documents/print' => 'documents#print'

  resources :documents

  root :to => 'main#index'

end

app/models/assembly.rb
class Assembly < ActiveRecord::Base
  belongs_to :documents
  attr_accessible :title
end

app/models/document.rb
class Document < ActiveRecord::Base
  belongs_to :user
  has_many :assemblies

  attr_accessible :image_url, :cover_image, :cover_image_url, :retained_cover_image, :remove_cover_image, :cover_image_name, :cover_image_uid
  attr_accessible :public, :title, :slug, :footer, :header, :main, :primary_color, :secondary_color, :assembly_id

  image_accessor :cover_image

  attr_accessor :image_url
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/assemblies_controller.rb
class AssembliesController < ApplicationController
  # GET /assemblies
  # GET /assemblies.json
  def index
    @assemblies = Assembly.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @assemblies }
    end
  end

  # GET /assemblies/1
  # GET /assemblies/1.json
  def show
    @assembly = Assembly.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @assembly }
    end
  end

  # GET /assemblies/new
  # GET /assemblies/new.json
  def new
    @assembly = Assembly.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @assembly }
    end
  end

  # GET /assemblies/1/edit
  def edit
    @assembly = Assembly.find(params[:id])
  end

  # POST /assemblies
  # POST /assemblies.json
  def create
    @assembly = Assembly.new(params[:assembly])

    respond_to do |format|
      if @assembly.save
        format.html { redirect_to @assembly, notice: 'Assembly was successfully created.' }
        format.json { render json: @assembly, status: :created, location: @assembly }
      else
        format.html { render action: "new" }
        format.json { render json: @assembly.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /assemblies/1
  # PUT /assemblies/1.json
  def update
    @assembly = Assembly.find(params[:id])

    respond_to do |format|
      if @assembly.update_attributes(params[:assembly])
        format.html { redirect_to @assembly, notice: 'Assembly was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @assembly.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assemblies/1
  # DELETE /assemblies/1.json
  def destroy
    @assembly = Assembly.find(params[:id])
    @assembly.destroy

    respond_to do |format|
      format.html { redirect_to assemblies_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assemblies_helper.rb
module AssembliesHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/assemblies/_form.html.erb
<%= form_for(@assembly) do |f| %>
  <% if @assembly.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@assembly.errors.count, "error") %> prohibited this assembly from being saved:</h2>

      <ul>
      <% @assembly.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/assemblies/edit.html.erb
<h1>Editing assembly</h1>

<%= render 'form' %>

<%= link_to 'Show', @assembly %> |
<%= link_to 'Back', assemblies_path %>

app/views/assemblies/index.html.erb
<h1>Listing assemblies</h1>

<table>
  <tr>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @assemblies.each do |assembly| %>
  <tr>
    <td><%= assembly.title %></td>
    <td><%= link_to 'Show', assembly %></td>
    <td><%= link_to 'Edit', edit_assembly_path(assembly) %></td>
    <td><%= link_to 'Destroy', assembly, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Assembly', new_assembly_path %>

app/views/assemblies/new.html.erb
<h1>New assembly</h1>

<%= render 'form' %>

<%= link_to 'Back', assemblies_path %>

app/views/assemblies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @assembly.title %>
</p>

<%= link_to 'Edit', edit_assembly_path(@assembly) %> |
<%= link_to 'Back', assemblies_path %>